/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.projeto.view;

import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import com.jgoodies.looks.plastic.theme.BrownSugar;
import com.jgoodies.looks.plastic.theme.DarkStar;
import com.jgoodies.looks.plastic.theme.DesertBlue;
import com.jgoodies.looks.plastic.theme.DesertBluer;
import com.jgoodies.looks.plastic.theme.ExperienceRoyale;
import com.jgoodies.looks.plastic.theme.Silver;
import com.jgoodies.looks.plastic.theme.SkyBlue;
import com.jgoodies.looks.plastic.theme.SkyBluer;
import com.jgoodies.looks.plastic.theme.SkyGreen;
import com.jgoodies.looks.plastic.theme.SkyPink;
import com.jgoodies.looks.plastic.theme.SkyYellow;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Iva
 */
public class GuiLogin extends javax.swing.JFrame {
        
    /**
     * Creates new form GuiPrincipal
     */
    public GuiLogin() {
        this.setLookAndFeel();
        initComponents();
    }

    private void setLookAndFeel(){
        try {
            PlasticLookAndFeel.setPlasticTheme(new SkyBlue());
                  try {
                      UIManager.setLookAndFeel("com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
                  } catch (InstantiationException ex) {
                      Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                      Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (UnsupportedLookAndFeelException ex) {
                      Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
                  }
           

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        
        SwingUtilities.updateComponentTreeUI(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbEsqueceu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lbEsqueceu = new javax.swing.JLabel();
        cbContinuar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbEsqueceu.setBackground(new java.awt.Color(204, 204, 204));
        jlbEsqueceu.setPreferredSize(new java.awt.Dimension(300, 250));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lbEsqueceu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbEsqueceu.setText("Esqueceu sua senha?");
        lbEsqueceu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEsqueceuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEsqueceuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEsqueceuMouseExited(evt);
            }
        });

        cbContinuar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbContinuar.setText("Continuar conectado");
        cbContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlbEsqueceuLayout = new javax.swing.GroupLayout(jlbEsqueceu);
        jlbEsqueceu.setLayout(jlbEsqueceuLayout);
        jlbEsqueceuLayout.setHorizontalGroup(
            jlbEsqueceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlbEsqueceuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlbEsqueceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlbEsqueceuLayout.createSequentialGroup()
                        .addComponent(cbContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lbEsqueceu)))
                .addContainerGap())
        );
        jlbEsqueceuLayout.setVerticalGroup(
            jlbEsqueceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlbEsqueceuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlbEsqueceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEsqueceu)
                    .addComponent(cbContinuar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlbEsqueceu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlbEsqueceu, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbContinuarActionPerformed

    private void lbEsqueceuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEsqueceuMouseEntered
        this.lbEsqueceu.setForeground(Color.blue);
    }//GEN-LAST:event_lbEsqueceuMouseEntered

    private void lbEsqueceuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEsqueceuMouseExited
        this.lbEsqueceu.setForeground(Color.white);
    }//GEN-LAST:event_lbEsqueceuMouseExited

    private void lbEsqueceuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEsqueceuMouseClicked
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEsqueceu().setVisible(true);
            }
        });
    }//GEN-LAST:event_lbEsqueceuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbContinuar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jlbEsqueceu;
    private javax.swing.JLabel lbEsqueceu;
    // End of variables declaration//GEN-END:variables
}
